services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_ENABLE_CPU_TEMPS: 'true'
      - DASHDOT_SHOW_DASH_VERSION: 'bottom_right'
    ports:
      - '80:3001'
    volumes:
      - /:/mnt/host:ro
